#!/usr/bin/env python3
"""
Parts Inventory to GL Reconciliation Tool

Usage:
  Create blank input template:
    python parts_rec.py template [--output monthly_inputs.xlsx]

  Run reconciliations:
    python parts_rec.py run --gl GL_Detail.xlsx --inputs monthly_inputs.xlsx [--output Parts_Rec_Output.xlsx]

GL Detail must have columns: Account, Journal, WIP, Reference, Acctg. Date, Amount $, Control,
  Control Description, Control2, Posting Description, Info, StatCnt
  (standard CDK Drive GL Detail export format)

Monthly inputs template is generated by the 'template' command.
"""

import argparse
import sys
import calendar
from datetime import date
from pathlib import Path

import pandas as pd
import openpyxl
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side
)
from openpyxl.utils import get_column_letter

# ---------------------------------------------------------------------------
# Month parsing
# ---------------------------------------------------------------------------

MONTH_MAP = {
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'SEPT': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12,
    'JANUARY': 1, 'FEBRUARY': 2, 'MARCH': 3, 'APRIL': 4, 'JUNE': 6,
    'JULY': 7, 'AUGUST': 8, 'SEPTEMBER': 9, 'OCTOBER': 10,
    'NOVEMBER': 11, 'DECEMBER': 12,
}

# Build a list sorted longest-first so "SEPT" matches before "SEP"
_ABBR_LIST = sorted(MONTH_MAP.keys(), key=len, reverse=True)


def _infer_year(control_month: int, acctg_dt) -> int | None:
    """
    Given a bare month number (no year) and an accounting date, return the
    most likely year.  Searches ±1 year from acctg_dt.year and picks the
    candidate that falls within −18 months to +2 months of acctg_dt,
    choosing the one closest in time.
    """
    ref = date(acctg_dt.year, acctg_dt.month, 1)
    best_year = None
    best_diff = float('inf')
    for offset in (-1, 0, 1):
        yr = acctg_dt.year + offset
        try:
            cand = date(yr, control_month, 1)
        except ValueError:
            continue
        delta = (cand - ref).days
        if -550 <= delta <= 62:          # ~18 months back, ~2 months forward
            if abs(delta) < best_diff:
                best_diff = abs(delta)
                best_year = yr
    return best_year


def parse_control_month(control_val, acctg_dt) -> tuple[int, int] | None:
    """
    Parse a single control/control2 value into (year, month) or None.

    Handles:
      - Bare month names:  NOV, DEC, SEPT, MARCH, …
      - Month + 2-digit year: JAN25, NOV24, SEPT24
      - Month + 4-digit year: JAN2025
    Returns None for invoice references, blank values, etc.
    """
    if not control_val:
        return None
    s = str(control_val).strip().upper()
    if s in ('NONE', '0', '', 'N/A'):
        return None

    for abbr in _ABBR_LIST:
        if not s.startswith(abbr):
            continue
        rest = s[len(abbr):]
        month_num = MONTH_MAP[abbr]

        if rest == '':
            # Bare month name
            yr = _infer_year(month_num, acctg_dt)
            return (yr, month_num) if yr else None

        if rest.isdigit():
            if len(rest) == 2:
                return (2000 + int(rest), month_num)
            if len(rest) == 4:
                return (int(rest), month_num)

        # e.g. "MARCH2025" already matched via "MARCH" above
        # If rest is non-numeric the prefix match was spurious (e.g. "B13…")
        break

    return None


def get_control_ym(row, acctg_dt) -> tuple[int, int] | None:
    """Try Control then Control2 for a month reference."""
    ym = parse_control_month(row.get('Control'), acctg_dt)
    if ym is None:
        ym = parse_control_month(row.get('Control2'), acctg_dt)
    return ym


def last_day(year: int, month: int) -> int:
    return calendar.monthrange(year, month)[1]


# ---------------------------------------------------------------------------
# GL classification
# ---------------------------------------------------------------------------


# Journal codes that represent inventory CONSUMPTION (sales, RO charges, counter invoices).
# These will never be timing differences for the inventory GL and are excluded from all
# timing-diff sections.  Standard CDK Drive journal codes:
#   60 = Service RO parts charges
#   61 = Warranty RO parts charges
#   62 = Counter/wholesale invoice parts charges
SALES_JOURNALS = {'60', '61', '62'}


def _has_nontrivial_control(row) -> bool:
    """Return True if either Control or Control2 contains a non-empty, non-trivial value."""
    for field in ('Control', 'Control2'):
        raw = row.get(field, '')
        try:
            if pd.isna(raw):
                continue
        except (TypeError, ValueError):
            pass
        v = str(raw).strip().upper()
        if v and v not in ('NONE', '0', 'N/A', '', 'NAN'):
            return True
    return False


def classify_gl(gl_df: pd.DataFrame, rec_year: int, rec_month: int):
    """
    Return (section1_df, section2_df, review_df) for a given reconciliation month.

    section1  – Posted in rec month, control = future month
                → "Parts in Accounting but not in Inventory (Not Received)"
                → SUBTRACT from GL side

    section2  – Posted AFTER rec month, control ≤ rec month
                → "In Physical, Not in GL" / Misc. Vendor Purchases
                → ADD to GL side

    review    – Posted AFTER rec month, has a non-trivial control value but it cannot
                be parsed as a month (e.g. a PO/invoice reference like B12331600, or
                a JE reference).  Excludes sales journal types (60/61/62) since those
                are inventory consumption entries and are never timing differences.
    """
    rec_start = date(rec_year, rec_month, 1)
    rec_end   = date(rec_year, rec_month, last_day(rec_year, rec_month))

    s1, s2, rv = [], [], []

    for _, row in gl_df.iterrows():
        raw_dt = row.get('Acctg. Date')
        if pd.isna(raw_dt):
            continue

        journal = str(row.get('Journal', '') or '').strip()
        if journal in SALES_JOURNALS:
            continue  # never a timing difference

        acctg_dt   = pd.Timestamp(raw_dt)
        acctg_date = acctg_dt.date()

        ym = get_control_ym(row, acctg_dt)

        if rec_start <= acctg_date <= rec_end:
            if ym and ym > (rec_year, rec_month):
                s1.append(row.to_dict())

        elif acctg_date > rec_end:
            if ym and ym <= (rec_year, rec_month):
                s2.append(row.to_dict())
            elif ym is None and _has_nontrivial_control(row):
                # Non-month reference in a purchase/adjustment journal — flag for review
                rv.append(row.to_dict())

    empty = pd.DataFrame(columns=gl_df.columns)
    s1_df = pd.DataFrame(s1) if s1 else empty.copy()
    s2_df = pd.DataFrame(s2) if s2 else empty.copy()
    rv_df = pd.DataFrame(rv) if rv else empty.copy()
    return s1_df, s2_df, rv_df


# ---------------------------------------------------------------------------
# Reconciliation calculation
# ---------------------------------------------------------------------------

def safe(val):
    try:
        return float(val) if not pd.isna(val) else 0.0
    except (TypeError, ValueError):
        return 0.0


def calculate_rec(row: dict, s1_total: float, s2_total: float) -> dict:
    """Build all reconciliation line items from input row + auto timing diffs."""

    # Parts side
    inventory  = safe(row.get('Inventory'))
    tires      = safe(row.get('Tires'))
    oil        = safe(row.get('Oil'))
    total_inv  = inventory + tires + oil
    paint      = safe(row.get('Paint_on_Mixer'))
    cores_new  = safe(row.get('Cores_New'))
    cores_used = safe(row.get('Cores_Used'))
    bowman     = safe(row.get('Bowman'))
    returns    = safe(row.get('Returns_11933'))
    claims     = safe(row.get('Claims'))
    ro_svc     = safe(row.get('Open_ROs_Service'))
    ro_ctr     = safe(row.get('Counter_Tickets_Parts'))
    open_ros   = ro_svc + ro_ctr

    step8 = total_inv + paint + cores_new + cores_used + bowman + returns + claims + open_ros

    # GL side
    gl_24200 = safe(row.get('GL_24200'))
    gl_24300 = safe(row.get('GL_24300'))
    gl_24401 = safe(row.get('GL_24401'))
    gl_other = safe(row.get('GL_Other'))
    gl_total = gl_24200 + gl_24300 + gl_24401 + gl_other

    mfg_slips = safe(row.get('Mfg_Packing_Slips'))
    prepaid   = safe(row.get('Prepaid_Special_Orders'))
    inv_adj   = safe(row.get('Inv_Adjustments_RPM'))
    oil_adj   = safe(row.get('Oil_Shop_Supply_Adj'))
    rad       = safe(row.get('Appreciation_Depreciation'))

    step17 = gl_total + mfg_slips + s2_total + prepaid - s1_total + inv_adj + oil_adj + rad
    step19 = step17 - step8
    step19_pct = step19 / gl_total if gl_total != 0 else None

    return dict(
        inventory=inventory, tires=tires, oil=oil, total_inv=total_inv,
        paint=paint, cores_new=cores_new, cores_used=cores_used, bowman=bowman,
        returns=returns, claims=claims, ro_svc=ro_svc, ro_ctr=ro_ctr, open_ros=open_ros,
        step8=step8,
        gl_24200=gl_24200, gl_24300=gl_24300, gl_24401=gl_24401,
        gl_other=gl_other, gl_total=gl_total,
        mfg_slips=mfg_slips, s2_total=s2_total, prepaid=prepaid,
        s1_total=s1_total, inv_adj=inv_adj, oil_adj=oil_adj, rad=rad,
        step17=step17, step8_ref=step8, step19=step19, step19_pct=step19_pct,
    )


# ---------------------------------------------------------------------------
# Excel helpers
# ---------------------------------------------------------------------------

MONEY_FMT   = '#,##0.00'
PCT_FMT     = '0.00%'
HDR_FILL    = PatternFill('solid', fgColor='1F4E79')   # dark blue
PARTS_FILL  = PatternFill('solid', fgColor='D6E4F0')   # light blue
GL_FILL     = PatternFill('solid', fgColor='E2EFDA')   # light green
VAR_POS     = PatternFill('solid', fgColor='FCE4D6')   # light red (GL > Parts)
VAR_NEG     = PatternFill('solid', fgColor='FCE4D6')
VAR_ZERO    = PatternFill('solid', fgColor='E2EFDA')   # green when close
SUB_FILL    = PatternFill('solid', fgColor='F2F2F2')
STEP8_FILL  = PatternFill('solid', fgColor='BDD7EE')   # medium blue
STEP17_FILL = PatternFill('solid', fgColor='A9D18E')   # medium green
STEP19_POS  = PatternFill('solid', fgColor='FCE4D6')
STEP19_NEG  = PatternFill('solid', fgColor='FCE4D6')
AUTO_FILL   = PatternFill('solid', fgColor='FFFACD')   # lemon yellow = auto-calculated

thin = Side(style='thin')
thick = Side(style='medium')
THIN_BORDER  = Border(left=thin,  right=thin,  top=thin,  bottom=thin)
THICK_BORDER = Border(left=thick, right=thick, top=thick, bottom=thick)


def _hdr(ws, row, col, value, bold=True, fill=None, align='left', size=11):
    c = ws.cell(row=row, column=col, value=value)
    c.font = Font(bold=bold, color='FFFFFF' if fill == HDR_FILL else '000000', size=size)
    if fill:
        c.fill = fill
    c.alignment = Alignment(horizontal=align, vertical='center', wrap_text=True)
    c.border = THIN_BORDER
    return c


def _val(ws, row, col, value, fmt=MONEY_FMT, fill=None, bold=False, align='right'):
    c = ws.cell(row=row, column=col, value=value)
    if fmt:
        c.number_format = fmt
    if fill:
        c.fill = fill
    c.font = Font(bold=bold, size=10)
    c.alignment = Alignment(horizontal=align, vertical='center')
    c.border = THIN_BORDER
    return c


def _lbl(ws, row, col, value, fill=None, bold=False, indent=0):
    c = ws.cell(row=row, column=col, value=value)
    c.font = Font(bold=bold, size=10)
    if fill:
        c.fill = fill
    c.alignment = Alignment(horizontal='left', vertical='center',
                             indent=indent, wrap_text=True)
    c.border = THIN_BORDER
    return c


def month_label(year: int, month: int) -> str:
    return date(year, month, 1).strftime('%b %Y')


# ---------------------------------------------------------------------------
# Sheet: individual reconciliation month
# ---------------------------------------------------------------------------

def write_rec_sheet(wb, rec_year, rec_month, calc, s1_df, s2_df, rv_df, inputs_row):
    title = month_label(rec_year, rec_month)
    ws = wb.create_sheet(title=title)

    ws.column_dimensions['A'].width = 4
    ws.column_dimensions['B'].width = 6
    ws.column_dimensions['C'].width = 50
    ws.column_dimensions['D'].width = 16
    ws.column_dimensions['E'].width = 8   # +/-
    ws.column_dimensions['F'].width = 16  # Amount
    ws.row_dimensions[1].height = 28

    # Title row
    ws.merge_cells('A1:F1')
    c = ws.cell(row=1, column=1, value=f'MONTH-END PARTS INVENTORY RECONCILIATION  –  {title.upper()}')
    c.font = Font(bold=True, size=13, color='FFFFFF')
    c.fill = HDR_FILL
    c.alignment = Alignment(horizontal='center', vertical='center')

    # Dealership info
    ws.cell(row=2, column=1, value='Dealership:').font = Font(bold=True, size=10)
    ws.cell(row=2, column=2, value=inputs_row.get('Dealership', '')).font = Font(size=10)

    r = 4  # current row

    # ── PARTS SECTION HEADER ──────────────────────────────────────────────
    ws.merge_cells(f'A{r}:F{r}')
    c = ws.cell(row=r, column=1, value='PARTS  (Inventory System)')
    c.font = Font(bold=True, size=11, color='FFFFFF')
    c.fill = PatternFill('solid', fgColor='2E74B5')
    c.alignment = Alignment(horizontal='left', vertical='center', indent=1)
    ws.row_dimensions[r].height = 18
    r += 1

    def parts_row(step, label, sub=None, amount=None, sign='+', fill=PARTS_FILL,
                  bold=False, auto=False):
        nonlocal r
        _lbl(ws, r, 1, step or '', fill=fill, bold=bold)
        _lbl(ws, r, 2, label, fill=fill, bold=bold, indent=1 if sub else 0)
        if sub:
            _lbl(ws, r, 3, sub, fill=SUB_FILL, indent=2)
        else:
            _lbl(ws, r, 3, '', fill=fill)
        _lbl(ws, r, 4, sign, fill=fill)
        f = AUTO_FILL if auto else (fill if amount is not None else fill)
        _val(ws, r, 5, amount, fill=f)
        ws.row_dimensions[r].height = 16
        r += 1

    # Step 1 – Inventory
    parts_row('1.', 'Month End Inventory Value (from MGR / Value by Source PDF)')
    parts_row('',   '', 'Inventory',   calc['inventory'], fill=SUB_FILL)
    parts_row('',   '', 'Tires',        calc['tires'],     fill=SUB_FILL)
    parts_row('',   '', 'Oil',          calc['oil'],       fill=SUB_FILL)

    # Total inventory bold line
    ws.merge_cells(f'B{r}:C{r}')
    _lbl(ws, r, 1, '', fill=STEP8_FILL)
    _lbl(ws, r, 2, 'Total Inventory  (Step 1)', fill=STEP8_FILL, bold=True)
    ws.cell(row=r, column=3).fill = STEP8_FILL
    _lbl(ws, r, 4, '=', fill=STEP8_FILL)
    _val(ws, r, 5, calc['total_inv'], fill=STEP8_FILL, bold=True)
    ws.row_dimensions[r].height = 16
    r += 1

    parts_row('2.',  'Paint on Mixer',                              calc['paint'])
    parts_row('2.',  'Cores in Stock (New)  – from MGR',            calc['cores_new'])
    parts_row('3.',  'Cores in Stock (Used) – from physical recap',  calc['cores_used'])
    parts_row('4.',  'Bowman',                                       calc['bowman'])
    parts_row('5.',  'Normal / Scheduled Parts Returns (Acct 11933)', calc['returns'])
    parts_row('6.',  'Claims  – from MGR',                           calc['claims'])
    parts_row('7.',  'Open Repair Orders & Invoices (Fast Lane)')
    parts_row('',    '', 'Service: Repair Orders',   calc['ro_svc'],  fill=SUB_FILL)
    parts_row('',    '', 'Parts: Counter Tickets',    calc['ro_ctr'],  fill=SUB_FILL)

    # Step 8 total
    ws.merge_cells(f'B{r}:C{r}')
    _lbl(ws, r, 1, '8.', fill=STEP8_FILL, bold=True)
    _lbl(ws, r, 2, 'Total Parts Adjusted Inventory Value  (Steps 1 – 7)', fill=STEP8_FILL, bold=True)
    ws.cell(row=r, column=3).fill = STEP8_FILL
    _lbl(ws, r, 4, '=', fill=STEP8_FILL)
    _val(ws, r, 5, calc['step8'], fill=STEP8_FILL, bold=True)
    ws.row_dimensions[r].height = 18
    step8_row = r
    r += 2

    # ── GL SECTION HEADER ─────────────────────────────────────────────────
    ws.merge_cells(f'A{r}:F{r}')
    c = ws.cell(row=r, column=1, value='ACCOUNTING  (General Ledger)')
    c.font = Font(bold=True, size=11, color='FFFFFF')
    c.fill = PatternFill('solid', fgColor='375623')
    c.alignment = Alignment(horizontal='left', vertical='center', indent=1)
    ws.row_dimensions[r].height = 18
    r += 1

    def gl_row(step, label, sub=None, amount=None, sign='+', fill=GL_FILL,
               bold=False, auto=False):
        nonlocal r
        _lbl(ws, r, 1, step or '', fill=fill, bold=bold)
        _lbl(ws, r, 2, label, fill=fill, bold=bold, indent=1 if sub else 0)
        if sub:
            _lbl(ws, r, 3, sub, fill=SUB_FILL, indent=2)
        else:
            _lbl(ws, r, 3, '', fill=fill)
        _lbl(ws, r, 4, sign, fill=fill)
        f = AUTO_FILL if auto else (fill if amount is not None else fill)
        _val(ws, r, 5, amount, fill=f)
        ws.row_dimensions[r].height = 16
        r += 1

    # Step 9 – GL balances
    gl_row('9.', f'GL Inventory Account Balances  (as of {title})')
    gl_row('',  '', 'Acct. 24200  –  Inventory',  calc['gl_24200'], fill=SUB_FILL)
    gl_row('',  '', 'Acct. 24300  –  Tires',       calc['gl_24300'], fill=SUB_FILL)
    gl_row('',  '', 'Acct. 24401  –  Oil',         calc['gl_24401'], fill=SUB_FILL)
    if calc['gl_other']:
        gl_row('', '', 'Other Account',             calc['gl_other'], fill=SUB_FILL)

    ws.merge_cells(f'B{r}:C{r}')
    _lbl(ws, r, 1, '', fill=STEP17_FILL)
    _lbl(ws, r, 2, 'Total GL Balance  (Step 9)', fill=STEP17_FILL, bold=True)
    ws.cell(row=r, column=3).fill = STEP17_FILL
    _lbl(ws, r, 4, '=', fill=STEP17_FILL)
    _val(ws, r, 5, calc['gl_total'], fill=STEP17_FILL, bold=True)
    ws.row_dimensions[r].height = 16
    r += 1

    gl_row('10.', 'Manufacturer Packing Slips  (In Physical, Not in GL)',
           amount=calc['mfg_slips'])

    # Step 11 – auto
    gl_row('11.', 'Misc. Vendor Purchases  (In Physical, Not in GL)  ← AUTO',
           amount=calc['s2_total'], auto=True)

    gl_row('12.', 'Prepaid Special Orders Not Received  (Neg. O/H)',
           amount=calc['prepaid'])

    # Step 13 – auto
    gl_row('13.', 'Parts in Accounting, Not in Inventory  (Posted Not Received)  ← AUTO',
           amount=calc['s1_total'], sign='−', auto=True)

    gl_row('14.', 'Inventory Adjustments  (RPM / MGR)', amount=calc['inv_adj'])
    gl_row('15.', 'Oil & Shop Supply Adjustment',        amount=calc['oil_adj'], sign='+/−')
    gl_row('16.', 'Appreciation / Depreciation  (RAD)',  amount=calc['rad'],     sign='+/−')

    # Step 17 total
    ws.merge_cells(f'B{r}:C{r}')
    _lbl(ws, r, 1, '17.', fill=STEP17_FILL, bold=True)
    _lbl(ws, r, 2, 'GL Adjusted Total  (Steps 9 – 16)', fill=STEP17_FILL, bold=True)
    ws.cell(row=r, column=3).fill = STEP17_FILL
    _lbl(ws, r, 4, '=', fill=STEP17_FILL)
    _val(ws, r, 5, calc['step17'], fill=STEP17_FILL, bold=True)
    ws.row_dimensions[r].height = 18
    r += 2

    # ── VARIANCE ──────────────────────────────────────────────────────────
    ws.merge_cells(f'A{r}:F{r}')
    c = ws.cell(row=r, column=1, value='VARIANCE')
    c.font = Font(bold=True, size=11, color='FFFFFF')
    c.fill = PatternFill('solid', fgColor='833C00')
    c.alignment = Alignment(horizontal='left', vertical='center', indent=1)
    ws.row_dimensions[r].height = 18
    r += 1

    var_fill = STEP19_POS if calc['step19'] != 0 else VAR_ZERO
    pct_val  = calc['step19_pct']

    _lbl(ws, r, 1, '18.', fill=var_fill, bold=True)
    _lbl(ws, r, 2, 'Total Parts Adjusted Inventory Value  (= Step 8)', fill=var_fill)
    _lbl(ws, r, 3, '', fill=var_fill)
    _lbl(ws, r, 4, '', fill=var_fill)
    _val(ws, r, 5, calc['step8_ref'], fill=var_fill, bold=True)
    ws.row_dimensions[r].height = 16
    r += 1

    _lbl(ws, r, 1, '19.', fill=var_fill, bold=True)
    _lbl(ws, r, 2, 'Parts Inventory Difference  (Step 17 − Step 18)', fill=var_fill)
    _lbl(ws, r, 3, '', fill=var_fill)
    _lbl(ws, r, 4, '', fill=var_fill)
    _val(ws, r, 5, calc['step19'], fill=var_fill, bold=True)
    ws.row_dimensions[r].height = 16
    r += 1

    _lbl(ws, r, 1, '', fill=var_fill)
    _lbl(ws, r, 2, 'Variance %  (Step 19 ÷ Total GL Balance)', fill=var_fill)
    _lbl(ws, r, 3, '', fill=var_fill)
    _lbl(ws, r, 4, '', fill=var_fill)
    _val(ws, r, 5, pct_val, fmt=PCT_FMT, fill=var_fill, bold=True)
    ws.row_dimensions[r].height = 16
    r += 2

    # ── TIMING DIFFERENCE DETAIL ──────────────────────────────────────────
    if not s1_df.empty or not s2_df.empty or not rv_df.empty:
        ws.merge_cells(f'A{r}:F{r}')
        c = ws.cell(row=r, column=1,
                    value='TIMING DIFFERENCE DETAIL  (from GL export  –  auto-calculated)')
        c.font = Font(bold=True, size=10, color='FFFFFF')
        c.fill = PatternFill('solid', fgColor='7B7B7B')
        c.alignment = Alignment(horizontal='left', vertical='center', indent=1)
        ws.row_dimensions[r].height = 16
        r += 1

        def _timing_section(df, heading, sign_note, row_fill):
            nonlocal r
            if df.empty:
                return
            ws.merge_cells(f'A{r}:F{r}')
            c = ws.cell(row=r, column=1, value=f'{heading}   ({sign_note})')
            c.font = Font(bold=True, size=10)
            c.fill = row_fill
            c.alignment = Alignment(horizontal='left', vertical='center', indent=1)
            ws.row_dimensions[r].height = 15
            r += 1

            # Column headers
            for col, hdr in enumerate(['Reference', 'Acctg. Date', 'Amount', 'Control',
                                        'Control2', 'Posting Description'], start=1):
                c = ws.cell(row=r, column=col, value=hdr)
                c.font = Font(bold=True, size=9)
                c.fill = PatternFill('solid', fgColor='D9D9D9')
                c.alignment = Alignment(horizontal='center')
                c.border = THIN_BORDER
            ws.row_dimensions[r].height = 14
            r += 1

            for _, row_data in df.iterrows():
                ws.cell(row=r, column=1, value=str(row_data.get('Reference', '') or '')).font = Font(size=9)
                dt_cell = ws.cell(row=r, column=2)
                raw = row_data.get('Acctg. Date')
                dt_cell.value = pd.Timestamp(raw).date() if not pd.isna(raw) else None
                dt_cell.number_format = 'MMM D, YYYY'
                dt_cell.font = Font(size=9)
                amt = ws.cell(row=r, column=3, value=row_data.get('Amount $'))
                amt.number_format = MONEY_FMT
                amt.font = Font(size=9)
                ws.cell(row=r, column=4, value=str(row_data.get('Control',  '') or '')).font = Font(size=9)
                ws.cell(row=r, column=5, value=str(row_data.get('Control2', '') or '')).font = Font(size=9)
                ws.cell(row=r, column=6, value=str(row_data.get('Posting Description', '') or '')).font = Font(size=9)
                for col in range(1, 7):
                    ws.cell(row=r, column=col).border = THIN_BORDER
                    ws.cell(row=r, column=col).fill = PatternFill('solid', fgColor='FAFAFA')
                ws.row_dimensions[r].height = 13
                r += 1

            # Section total
            tot = df['Amount $'].sum() if 'Amount $' in df.columns else 0.0
            ws.cell(row=r, column=2, value='TOTAL').font = Font(bold=True, size=9)
            c = ws.cell(row=r, column=3, value=tot)
            c.number_format = MONEY_FMT
            c.font = Font(bold=True, size=9)
            c.fill = row_fill
            for col in range(1, 7):
                ws.cell(row=r, column=col).border = THIN_BORDER
            ws.row_dimensions[r].height = 14
            r += 2

        _timing_section(s1_df, 'Section A – Posted Not Received  (Step 13)',
                        'subtract from GL', PatternFill('solid', fgColor='FCE4D6'))
        _timing_section(s2_df, 'Section B – In Physical, Not in GL  (Step 11)',
                        'add to GL', PatternFill('solid', fgColor='E2EFDA'))
        if not rv_df.empty:
            _timing_section(rv_df, 'Section C – Review Needed  (non-month control, posted after rec month)',
                            'manual review', PatternFill('solid', fgColor='FFF2CC'))


# ---------------------------------------------------------------------------
# Sheet: Summary / Trend
# ---------------------------------------------------------------------------

def write_summary_sheet(wb, results: list[dict]):
    ws = wb.create_sheet(title='Summary', index=0)

    cols = [
        ('Month',                        14),
        ('Parts Adj. Value\n(Step 8)',    16),
        ('GL Balance\n(Raw)',             16),
        ('GL Adj. Total\n(Step 17)',      16),
        ('Variance $\n(Step 17 − Step 8)',18),
        ('Variance %',                   12),
        ('Posted Not\nReceived (Step 13)',18),
        ('In Physical\nNot in GL (Step 11)',20),
        ('Open ROs\n& Tickets',          16),
        ('Cores\n(New + Used)',           14),
        ('RAD',                          12),
    ]

    ws.merge_cells('A1:K1')
    c = ws.cell(row=1, column=1, value='PARTS INVENTORY RECONCILIATION  –  MULTI-MONTH SUMMARY')
    c.font = Font(bold=True, size=13, color='FFFFFF')
    c.fill = HDR_FILL
    c.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[1].height = 28

    for col, (header, width) in enumerate(cols, start=1):
        ws.column_dimensions[get_column_letter(col)].width = width
        c = ws.cell(row=2, column=col, value=header)
        c.font = Font(bold=True, size=10, color='FFFFFF')
        c.fill = PatternFill('solid', fgColor='2E74B5')
        c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        c.border = THIN_BORDER
        ws.row_dimensions[2].height = 36

    for row_i, res in enumerate(results, start=3):
        calc = res['calc']
        year, month = res['year'], res['month']
        var = calc['step19']

        var_fill = PatternFill('solid', fgColor='FCE4D6') if abs(var) > 1 else \
                   PatternFill('solid', fgColor='E2EFDA')

        data = [
            (month_label(year, month), None, 'left'),
            (calc['step8'],            MONEY_FMT, 'right'),
            (calc['gl_total'],         MONEY_FMT, 'right'),
            (calc['step17'],           MONEY_FMT, 'right'),
            (var,                      MONEY_FMT, 'right'),
            (calc['step19_pct'],       PCT_FMT,   'right'),
            (calc['s1_total'],         MONEY_FMT, 'right'),
            (calc['s2_total'],         MONEY_FMT, 'right'),
            (calc['open_ros'],         MONEY_FMT, 'right'),
            (calc['cores_new'] + calc['cores_used'], MONEY_FMT, 'right'),
            (calc['rad'],              MONEY_FMT, 'right'),
        ]

        for col, (val, fmt, align) in enumerate(data, start=1):
            c = ws.cell(row=row_i, column=col, value=val)
            if fmt:
                c.number_format = fmt
            c.alignment = Alignment(horizontal=align, vertical='center')
            c.border = THIN_BORDER
            c.font = Font(size=10)
            if col == 5:
                c.fill = var_fill
                c.font = Font(size=10, bold=True)

        ws.row_dimensions[row_i].height = 16

    # Totals row
    tr = len(results) + 3
    ws.cell(row=tr, column=1, value='TOTAL / AVG').font = Font(bold=True, size=10)
    ws.cell(row=tr, column=1).border = THIN_BORDER
    sum_cols = {2: 'step8', 4: 'step17', 5: 'step19', 7: 's1_total',
                8: 's2_total', 9: 'open_ros', 11: 'rad'}
    for col, key in sum_cols.items():
        total = sum(r['calc'][key] for r in results)
        c = ws.cell(row=tr, column=col, value=total)
        c.number_format = MONEY_FMT
        c.font = Font(bold=True, size=10)
        c.border = THIN_BORDER
        c.fill = PatternFill('solid', fgColor='D9D9D9')

    avg_pct = sum(r['calc']['step19_pct'] or 0 for r in results) / len(results) if results else 0
    c = ws.cell(row=tr, column=6, value=avg_pct)
    c.number_format = PCT_FMT
    c.font = Font(bold=True, size=10)
    c.border = THIN_BORDER
    c.fill = PatternFill('solid', fgColor='D9D9D9')
    ws.row_dimensions[tr].height = 18

    # Legend
    lr = tr + 2
    ws.cell(row=lr, column=1, value='Legend:').font = Font(bold=True, size=9)
    items = [
        (PatternFill('solid', fgColor='FCE4D6'), 'Variance present  (GL ≠ Inventory)'),
        (PatternFill('solid', fgColor='E2EFDA'), 'Balanced  (no material variance)'),
        (AUTO_FILL,                              'Auto-calculated from GL Detail export'),
    ]
    for i, (fill, label) in enumerate(items):
        c = ws.cell(row=lr + i, column=2)
        c.fill = fill
        c.border = THIN_BORDER
        ws.cell(row=lr + i, column=3, value=label).font = Font(size=9)


# ---------------------------------------------------------------------------
# Sheet: GL Analysis (all timing diff entries across all months)
# ---------------------------------------------------------------------------

def write_gl_analysis_sheet(wb, results: list[dict]):
    ws = wb.create_sheet(title='GL Analysis')

    ws.merge_cells('A1:H1')
    c = ws.cell(row=1, column=1, value='GL TIMING DIFFERENCE ANALYSIS  –  ALL MONTHS')
    c.font = Font(bold=True, size=12, color='FFFFFF')
    c.fill = HDR_FILL
    c.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[1].height = 24

    headers = ['Rec Month', 'Section', 'Account', 'Reference',
               'Acctg. Date', 'Amount $', 'Control', 'Control2', 'Posting Description']
    widths   = [12, 35, 10, 16, 14, 14, 12, 12, 30]
    for col, (h, w) in enumerate(zip(headers, widths), start=1):
        ws.column_dimensions[get_column_letter(col)].width = w
        c = ws.cell(row=2, column=col, value=h)
        c.font = Font(bold=True, size=10, color='FFFFFF')
        c.fill = PatternFill('solid', fgColor='2E74B5')
        c.alignment = Alignment(horizontal='center', vertical='center')
        c.border = THIN_BORDER
    ws.row_dimensions[2].height = 18

    row = 3
    for res in results:
        ml = month_label(res['year'], res['month'])
        for section, df, label, fill in [
            ('A – Posted Not Received (Step 13)',  res['s1_df'], 'subtract', PatternFill('solid', fgColor='FCE4D6')),
            ('B – In Physical, Not in GL (Step 11)', res['s2_df'], 'add',   PatternFill('solid', fgColor='E2EFDA')),
            ('C – Review Needed',                  res['rv_df'], 'review',  PatternFill('solid', fgColor='FFF2CC')),
        ]:
            if df.empty:
                continue
            for _, dr in df.iterrows():
                raw_dt = dr.get('Acctg. Date')
                dt_val = pd.Timestamp(raw_dt).date() if not pd.isna(raw_dt) else None
                vals = [
                    ml, section,
                    str(dr.get('Account', '') or ''),
                    str(dr.get('Reference', '') or ''),
                    dt_val,
                    dr.get('Amount $'),
                    str(dr.get('Control',  '') or ''),
                    str(dr.get('Control2', '') or ''),
                    str(dr.get('Posting Description', '') or ''),
                ]
                for col, v in enumerate(vals, start=1):
                    c = ws.cell(row=row, column=col, value=v)
                    c.font = Font(size=9)
                    c.fill = fill
                    c.border = THIN_BORDER
                    if col == 5 and v:
                        c.number_format = 'MMM D, YYYY'
                    if col == 6:
                        c.number_format = MONEY_FMT
                ws.row_dimensions[row].height = 13
                row += 1


# ---------------------------------------------------------------------------
# Input template generator
# ---------------------------------------------------------------------------

TEMPLATE_COLUMNS = [
    ('Month',                    'YYYY-MM  (e.g. 2025-11)',   14),
    ('Dealership',               'Dealership name',           20),
    ('Inventory',                'MGR – inventory component', 16),
    ('Tires',                    'MGR – tires',               14),
    ('Oil',                      'MGR – oil',                 14),
    ('Paint_on_Mixer',           'Paint on mixer',            16),
    ('Cores_New',                'Cores in stock new (MGR)',  18),
    ('Cores_Used',               'Cores in stock used (phys. recap)', 22),
    ('Bowman',                   'Bowman',                    14),
    ('Returns_11933',            'Normal scheduled returns (Acct 11933)', 24),
    ('Claims',                   'Claims – from MGR',         14),
    ('Open_ROs_Service',         'Fast Lane – service ROs',   20),
    ('Counter_Tickets_Parts',    'Fast Lane – parts counter tickets', 24),
    ('Mfg_Packing_Slips',        'Mfg packing slips (manual)', 22),
    ('Prepaid_Special_Orders',   'Prepaid special orders (neg O/H)', 24),
    ('Inv_Adjustments_RPM',      'Inventory adjustments RPM', 22),
    ('Oil_Shop_Supply_Adj',      'Oil & shop supply adjustment', 22),
    ('Appreciation_Depreciation','Appreciation / depreciation (RAD)', 24),
    ('GL_24200',                 'GL balance – Acct. 24200',  20),
    ('GL_24300',                 'GL balance – Acct. 24300',  20),
    ('GL_24401',                 'GL balance – Acct. 24401',  20),
    ('GL_Other',                 'GL balance – other account (optional)', 28),
]


def create_template(output_path: str):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = 'Monthly Inputs'

    ws.merge_cells('A1:V1')
    c = ws.cell(row=1, column=1, value='PARTS REC MONTHLY INPUTS  –  fill one row per month being reconciled')
    c.font = Font(bold=True, size=12, color='FFFFFF')
    c.fill = HDR_FILL
    c.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[1].height = 24

    ws.merge_cells('A2:V2')
    c = ws.cell(row=2, column=1,
                value='Cells highlighted yellow are auto-calculated from the GL Detail export.  '
                      'All other Amount cells require manual entry from CDK PDF reports.')
    c.font = Font(italic=True, size=9)
    c.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
    ws.row_dimensions[2].height = 28

    for col, (name, desc, width) in enumerate(TEMPLATE_COLUMNS, start=1):
        ws.column_dimensions[get_column_letter(col)].width = width
        c = ws.cell(row=3, column=col, value=name)
        c.font = Font(bold=True, size=10, color='FFFFFF')
        c.fill = PatternFill('solid', fgColor='2E74B5')
        c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        c.border = THIN_BORDER

        c2 = ws.cell(row=4, column=col, value=desc)
        c2.font = Font(italic=True, size=8, color='595959')
        c2.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        c2.border = THIN_BORDER
        c2.fill = PatternFill('solid', fgColor='F2F2F2')

    ws.row_dimensions[3].height = 22
    ws.row_dimensions[4].height = 32

    # 6 blank data rows
    for row in range(5, 11):
        for col in range(1, len(TEMPLATE_COLUMNS) + 1):
            c = ws.cell(row=row, column=col)
            c.border = THIN_BORDER
            if col > 2:
                c.number_format = MONEY_FMT
        ws.row_dimensions[row].height = 16

    # Instructions sheet
    iws = wb.create_sheet('Instructions')
    instructions = [
        ('PARTS REC TOOL  –  HOW TO USE', True, 14),
        ('', False, 10),
        ('STEP 1 – Export GL Detail from Drive', True, 11),
        ('  Run the GL Detail report for all inventory GL accounts (24200, 24300, 24401).', False, 10),
        ('  Date range: start of the EARLIEST month you are reconciling → today.', False, 10),
        ('  Save as .xlsx. This is your --gl input file.', False, 10),
        ('', False, 10),
        ('STEP 2 – Fill in Monthly Inputs', True, 11),
        ('  Open this template and add one row per month you are reconciling.', False, 10),
        ('  Month column format: YYYY-MM  (e.g. 2025-11 for November 2025)', False, 10),
        ('  Values come from CDK PDF reports (MGR, physical recap, RAD, Fast Lane).', False, 10),
        ('  GL balance columns: enter the AS-OF balance from the GL balance inquiry,', False, 10),
        ('    NOT calculated from the GL detail.', False, 10),
        ('', False, 10),
        ('STEP 3 – Run the tool', True, 11),
        ('  python parts_rec.py run --gl GL_Detail.xlsx --inputs monthly_inputs.xlsx', False, 10),
        ('  Output file: Parts_Rec_Output.xlsx  (or specify with --output)', False, 10),
        ('', False, 10),
        ('AUTO-CALCULATED ITEMS', True, 11),
        ('  Step 11 – Misc. Vendor Purchases (In Physical, Not in GL):', False, 10),
        ('    GL entries posted AFTER rec month where Control/Control2 ≤ rec month.', False, 10),
        ('  Step 13 – Posted Not Received (Parts in Accounting, Not in Inventory):', False, 10),
        ('    GL entries posted IN rec month where Control/Control2 = future month.', False, 10),
        ('  A "Review Needed" section flags post-rec-month entries with non-month controls', False, 10),
        ('  (e.g. JE core returns) — you can manually add these to the inputs if needed.', False, 10),
        ('', False, 10),
        ('CONTROL FIELD PARSING', True, 11),
        ('  Month abbreviations recognized: JAN FEB MAR APR MAY JUN JUL AUG SEPT OCT NOV DEC', False, 10),
        ('  Also: JANUARY FEBRUARY MARCH APRIL JUNE JULY AUGUST SEPTEMBER OCTOBER NOVEMBER DECEMBER', False, 10),
        ('  Year suffix: JAN25, NOV24, SEPT24  (two-digit year after month abbreviation)', False, 10),
        ('  Both the "Control" and "Control2" columns in the GL export are checked.', False, 10),
    ]

    iws.column_dimensions['A'].width = 90
    for i, (text, bold, size) in enumerate(instructions, start=1):
        c = iws.cell(row=i, column=1, value=text)
        c.font = Font(bold=bold, size=size)
        if bold and text:
            c.fill = PatternFill('solid', fgColor='D6E4F0')
        iws.row_dimensions[i].height = 16 if text else 8

    wb.save(output_path)
    print(f'Template saved to: {output_path}')


# ---------------------------------------------------------------------------
# Main runner
# ---------------------------------------------------------------------------

def run(gl_path: str, inputs_path: str, output_path: str):
    print(f'Reading GL Detail: {gl_path}')
    gl_df = pd.read_excel(gl_path, dtype={'Account': str, 'Journal': str})

    # Normalise column names (strip whitespace)
    gl_df.columns = [str(c).strip() for c in gl_df.columns]

    required = ['Acctg. Date', 'Amount $', 'Control']
    missing  = [c for c in required if c not in gl_df.columns]
    if missing:
        sys.exit(f'GL Detail is missing columns: {missing}\n'
                 f'Found columns: {list(gl_df.columns)}')

    # Fill missing Control2
    if 'Control2' not in gl_df.columns:
        gl_df['Control2'] = ''

    print(f'Reading Monthly Inputs: {inputs_path}')
    inp_df = pd.read_excel(inputs_path, sheet_name='Monthly Inputs', header=2,
                           skiprows=[3])  # row 3 = col names, row 4 = descriptions → skip
    inp_df.columns = [str(c).strip() for c in inp_df.columns]
    inp_df = inp_df.dropna(subset=['Month'])
    inp_df = inp_df[inp_df['Month'].astype(str).str.strip() != '']

    results = []
    for _, inp_row in inp_df.iterrows():
        month_str = str(inp_row['Month']).strip()
        try:
            rec_year, rec_month = _parse_month(month_str)
        except ValueError as e:
            print(f'  WARNING: skipping row – {e}')
            continue

        print(f'  Processing {month_label(rec_year, rec_month)} …', end='')
        s1_df, s2_df, rv_df = classify_gl(gl_df, rec_year, rec_month)
        s1_total = s1_df['Amount $'].sum() if not s1_df.empty else 0.0
        s2_total = s2_df['Amount $'].sum() if not s2_df.empty else 0.0
        print(f'  Section A (step 13): ${s1_total:,.2f}   Section B (step 11): ${s2_total:,.2f}'
              f'   Review: {len(rv_df)} entries')

        calc = calculate_rec(inp_row.to_dict(), s1_total, s2_total)
        results.append(dict(year=rec_year, month=rec_month, calc=calc,
                            s1_df=s1_df, s2_df=s2_df, rv_df=rv_df,
                            inputs=inp_row.to_dict()))

    if not results:
        sys.exit('No valid months found in inputs file.')

    print(f'\nWriting output: {output_path}')
    wb = openpyxl.Workbook()
    wb.remove(wb.active)   # remove default empty sheet

    write_summary_sheet(wb, results)
    for res in results:
        write_rec_sheet(wb, res['year'], res['month'], res['calc'],
                        res['s1_df'], res['s2_df'], res['rv_df'], res['inputs'])
    write_gl_analysis_sheet(wb, results)

    wb.save(output_path)
    print('Done.')

    # Print quick summary
    print('\n' + '─' * 70)
    print(f'{"Month":<12} {"Parts Adj":>14} {"GL Adj":>14} {"Variance $":>14} {"Variance %":>10}')
    print('─' * 70)
    for res in results:
        c = res['calc']
        pct = f"{c['step19_pct']:.1%}" if c['step19_pct'] is not None else 'n/a'
        print(f'{month_label(res["year"],res["month"]):<12} '
              f'{c["step8"]:>14,.2f} {c["step17"]:>14,.2f} '
              f'{c["step19"]:>14,.2f} {pct:>10}')
    print('─' * 70)


def _parse_month(s: str) -> tuple[int, int]:
    s = s.strip()
    for sep in ('-', '/'):
        if sep in s:
            parts = s.split(sep)
            return int(parts[0]), int(parts[1])
    raise ValueError(f'Cannot parse month "{s}" – expected YYYY-MM or YYYY/MM')


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Parts Inventory / GL Reconciliation Tool',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest='command', required=True)

    # template sub-command
    tp = sub.add_parser('template', help='Create a blank monthly inputs template')
    tp.add_argument('--output', default='monthly_inputs.xlsx',
                    help='Output path for the template  (default: monthly_inputs.xlsx)')

    # run sub-command
    rp = sub.add_parser('run', help='Run reconciliations')
    rp.add_argument('--gl',     required=True, help='Path to GL Detail Excel export')
    rp.add_argument('--inputs', required=True, help='Path to filled-in monthly inputs Excel')
    rp.add_argument('--output', default='Parts_Rec_Output.xlsx',
                    help='Output path  (default: Parts_Rec_Output.xlsx)')

    args = parser.parse_args()

    if args.command == 'template':
        create_template(args.output)
    elif args.command == 'run':
        run(args.gl, args.inputs, args.output)


if __name__ == '__main__':
    main()
